import { db } from "../db";
import { orders, users, merchants } from "@db/schema";
import { eq, and, gte, lte, between, sql } from "drizzle-orm";

interface ExportFilters {
  startDate?: Date;
  endDate?: Date;
  status?: string;
  minAmount?: number;
  maxAmount?: number;
}

interface PaymentRecord {
  id: number;
  userId: number;
  merchantId: number;
  totalAmount: number;
  status: string;
  paymentMethod: string;
  createdAt: Date;
  userName?: string;
  merchantName?: string;
}

export async function exportPaymentHistoryCSV(
  userId: number,
  filters: ExportFilters
): Promise<string> {
  const payments = await getFilteredPayments(userId, filters);

  // CSV Header
  let csv = "Order ID,Date,Merchant,Amount,Payment Method,Status\n";

  // CSV Rows
  for (const payment of payments) {
    const date = new Date(payment.createdAt).toLocaleString();
    const merchant = payment.merchantName || "Unknown";
    const amount = `$${payment.totalAmount.toFixed(2)}`;
    const method = payment.paymentMethod || "N/A";
    const status = payment.status;

    csv += `${payment.id},"${date}","${merchant}",${amount},${method},${status}\n`;
  }

  return csv;
}

export async function exportPaymentHistoryPDF(
  userId: number,
  filters: ExportFilters
): Promise<string> {
  const payments = await getFilteredPayments(userId, filters);
  const user = await db.query.users.findFirst({
    where: eq(users.id, userId),
  });

  // Generate HTML for PDF
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 40px;
      color: #333;
    }
    .header {
      text-align: center;
      margin-bottom: 30px;
      border-bottom: 2px solid #2563eb;
      padding-bottom: 20px;
    }
    .header h1 {
      color: #2563eb;
      margin: 0;
    }
    .header p {
      color: #666;
      margin: 5px 0;
    }
    .info {
      margin-bottom: 30px;
    }
    .info p {
      margin: 5px 0;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }
    th {
      background-color: #2563eb;
      color: white;
      padding: 12px;
      text-align: left;
      font-weight: bold;
    }
    td {
      padding: 10px 12px;
      border-bottom: 1px solid #ddd;
    }
    tr:nth-child(even) {
      background-color: #f9fafb;
    }
    .status-completed {
      color: #16a34a;
      font-weight: bold;
    }
    .status-pending {
      color: #ca8a04;
      font-weight: bold;
    }
    .status-failed {
      color: #dc2626;
      font-weight: bold;
    }
    .summary {
      margin-top: 30px;
      padding: 20px;
      background-color: #f0f9ff;
      border-left: 4px solid #2563eb;
    }
    .summary h3 {
      margin-top: 0;
      color: #2563eb;
    }
    .footer {
      margin-top: 40px;
      text-align: center;
      color: #999;
      font-size: 12px;
      border-top: 1px solid #ddd;
      padding-top: 20px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Payment History Report</h1>
    <p>Smart Store Payment System</p>
  </div>

  <div class="info">
    <p><strong>Account:</strong> ${user?.email || "Unknown"}</p>
    <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
    ${filters.startDate ? `<p><strong>Period:</strong> ${filters.startDate.toLocaleDateString()} - ${filters.endDate?.toLocaleDateString() || "Present"}</p>` : ""}
  </div>

  <table>
    <thead>
      <tr>
        <th>Order ID</th>
        <th>Date</th>
        <th>Merchant</th>
        <th>Amount</th>
        <th>Payment Method</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      ${payments
        .map(
          (payment) => `
        <tr>
          <td>#${payment.id}</td>
          <td>${new Date(payment.createdAt).toLocaleString()}</td>
          <td>${payment.merchantName || "Unknown"}</td>
          <td>$${payment.totalAmount.toFixed(2)}</td>
          <td>${payment.paymentMethod || "N/A"}</td>
          <td class="status-${payment.status}">${payment.status}</td>
        </tr>
      `
        )
        .join("")}
    </tbody>
  </table>

  <div class="summary">
    <h3>Summary</h3>
    <p><strong>Total Transactions:</strong> ${payments.length}</p>
    <p><strong>Total Amount:</strong> $${payments.reduce((sum, p) => sum + p.totalAmount, 0).toFixed(2)}</p>
    <p><strong>Completed:</strong> ${payments.filter((p) => p.status === "completed").length}</p>
    <p><strong>Pending:</strong> ${payments.filter((p) => p.status === "pending").length}</p>
    <p><strong>Failed:</strong> ${payments.filter((p) => p.status === "failed").length}</p>
  </div>

  <div class="footer">
    <p>This is an automated report generated by SSP (Smart Store Payment)</p>
    <p>For questions or support, visit https://ssp.click</p>
  </div>
</body>
</html>
  `;

  return html;
}

async function getFilteredPayments(
  userId: number,
  filters: ExportFilters
): Promise<PaymentRecord[]> {
  const conditions = [eq(orders.userId, userId)];

  if (filters.startDate) {
    conditions.push(gte(orders.createdAt, filters.startDate));
  }

  if (filters.endDate) {
    conditions.push(lte(orders.createdAt, filters.endDate));
  }

  if (filters.status && filters.status !== "all") {
    conditions.push(eq(orders.status, filters.status));
  }

  if (filters.minAmount !== undefined) {
    conditions.push(gte(orders.totalAmount, filters.minAmount));
  }

  if (filters.maxAmount !== undefined) {
    conditions.push(lte(orders.totalAmount, filters.maxAmount));
  }

  const results = await db
    .select({
      id: orders.id,
      userId: orders.userId,
      merchantId: orders.merchantId,
      totalAmount: orders.totalAmount,
      status: orders.status,
      paymentMethod: orders.paymentMethod,
      createdAt: orders.createdAt,
      merchantName: merchants.name,
    })
    .from(orders)
    .leftJoin(merchants, eq(orders.merchantId, merchants.id))
    .where(and(...conditions))
    .orderBy(sql`${orders.createdAt} DESC`)
    .limit(1000); // Limit to prevent excessive data

  return results as PaymentRecord[];
}

export async function exportLoginHistoryCSV(userId: number): Promise<string> {
  const { loginHistory } = await import("@db/schema");

  const history = await db.query.loginHistory.findMany({
    where: eq(loginHistory.userId, userId),
    orderBy: (loginHistory, { desc }) => [desc(loginHistory.createdAt)],
    limit: 1000,
  });

  // CSV Header
  let csv = "Date,Login Method,Status,IP Address,Location,Device\n";

  // CSV Rows
  for (const login of history) {
    const date = new Date(login.createdAt).toLocaleString();
    const method = login.loginMethod || "unknown";
    const status = login.status;
    const ip = login.ipAddress || "N/A";
    const location = login.location || "Unknown";
    const device = (login.userAgent || "Unknown").substring(0, 50);

    csv += `"${date}",${method},${status},"${ip}","${location}","${device}"\n`;
  }

  return csv;
}
